window.JADE_RESOURCES = [
  {
    "id": "aac-electrical-a",
    "week": 1,
    "type": "Video",
    "status": "Required",
    "title": "Electrical Quantities A — Voltage, Current, Resistance, and Charge",
    "provider": "North Seattle Community College / All About Circuits",
    "url": "https://www.allaboutcircuits.com/video-lectures/electrical-quantities-a/",
    "focus": "Physical meaning of voltage, current, resistance, and charge.",
    "action": "Explain each quantity in plain language and state whether it is measured across or through a circuit."
  },
  {
    "id": "aac-electrical-b",
    "week": 1,
    "type": "Video",
    "status": "Required",
    "title": "Electrical Quantities B — Ohm’s Law and Electrical Power",
    "provider": "North Seattle Community College / All About Circuits",
    "url": "https://www.allaboutcircuits.com/video-lectures/electrical-quantities-b/",
    "focus": "Ohm’s law, direct/inverse relationships, and power.",
    "action": "Predict the relationship before calculating; then verify the units."
  },
  {
    "id": "aac-notation",
    "week": 1,
    "type": "Video",
    "status": "Required",
    "title": "Technical Notation — Engineering Notation and SI Prefixes",
    "provider": "North Seattle Community College / All About Circuits",
    "url": "https://www.allaboutcircuits.com/video-lectures/technical-notation/",
    "focus": "milli, micro, nano, kilo, mega, and engineering notation.",
    "action": "Convert at least ten values between base units and common prefixes."
  },
  {
    "id": "fluke-dmm",
    "week": 3,
    "type": "Written",
    "status": "Required",
    "title": "How to Use a Multimeter — Comprehensive Guide",
    "provider": "Fluke",
    "url": "https://www.fluke.com/en/learn/blog/maintenance-monitoring/how-to-use-a-multimeter-guide",
    "focus": "DMM functions, jacks, continuity, resistance, voltage, diode test, and safety.",
    "action": "Before the next measurement, say quantity → function → jack → connection → expected reading."
  },
  {
    "id": "keysight-psu",
    "week": 3,
    "type": "Video",
    "status": "Required",
    "title": "Bench Power Supply Basics",
    "provider": "Keysight Technologies",
    "url": "https://www.keysight.com/us/en/learn/course.bench-power-supply-basics.html",
    "focus": "Voltage setting, current limit, CV/CC behavior, and safe first power.",
    "action": "Set a conservative current limit and predict whether the supply should remain in CV mode."
  },
  {
    "id": "keysight-cvcc",
    "week": 3,
    "type": "Video",
    "status": "Required",
    "title": "Constant Voltage and Constant Current Modes",
    "provider": "Keysight Technologies",
    "url": "https://www.keysight.com/zz/en/assets/6123-1426/lessons/0027BenchPowerSupplyBasics004Using6UnderstandingConstantVoltageandConstantCurrentModes.html",
    "focus": "Interpret current-limit behavior as evidence, not as a setting to defeat.",
    "action": "Explain what a sudden switch into CC mode tells you about the load."
  },
  {
    "id": "tektronix-scope",
    "week": 3,
    "type": "Written",
    "status": "Required",
    "title": "How to Use an Oscilloscope and Probe — Step-by-Step",
    "provider": "Tektronix",
    "url": "https://www.tek.com/en/documents/primer/setting-and-using-oscilloscope",
    "focus": "Grounding, probe connection, volts/div, time/div, triggering, probe compensation, and basic measurement.",
    "action": "Capture a known square wave and preserve the settings that make the capture reproducible."
  },
  {
    "id": "aac-kcl-kvl",
    "week": 2,
    "type": "Video",
    "status": "Required",
    "title": "Ohm’s Law, Kirchhoff’s Laws, and Power Equations",
    "provider": "All About Circuits",
    "url": "https://www.youtube.com/watch?v=ezvZuaVzoys",
    "focus": "KCL/KVL as conservation rules and diagnostic tools.",
    "action": "Write the signed equation before substituting numbers."
  },
  {
    "id": "aac-troubleshoot",
    "week": 4,
    "type": "Video",
    "status": "Required",
    "title": "Troubleshooting Series-Parallel Circuits",
    "provider": "North Seattle Community College / All About Circuits",
    "url": "https://www.allaboutcircuits.com/video-lectures/troubleshooting-series-parallel-circuits/",
    "focus": "Expected values, fault patterns, and measurements that shrink the fault space.",
    "action": "Write expected values before taking the next troubleshooting measurement."
  },
  {
    "id": "ti-board",
    "week": 4,
    "type": "Video",
    "status": "Required",
    "title": "Board Level Troubleshooting",
    "provider": "Texas Instruments",
    "url": "https://www.ti.com/video/5971802514001",
    "focus": "Board-level troubleshooting and controlled substitution.",
    "action": "Identify what evidence a substitution would prove and what it would not prove."
  },
  {
    "id": "adafruit-solder",
    "week": 5,
    "type": "Written",
    "status": "Required",
    "title": "Making a Good Solder Joint",
    "provider": "Adafruit Learning System",
    "url": "https://learn.adafruit.com/adafruit-guide-excellent-soldering/making-a-good-solder-joint",
    "focus": "Heating the joint, solder flow, cooling, and workmanship.",
    "action": "Produce and inspect five joints before attempting rework."
  },
  {
    "id": "adafruit-defects",
    "week": 5,
    "type": "Written",
    "status": "Required",
    "title": "Common Soldering Problems",
    "provider": "Adafruit Learning System",
    "url": "https://learn.adafruit.com/adafruit-guide-excellent-soldering/common-problems",
    "focus": "Cold/disturbed joints, bridges, insufficient wetting, excess solder, lifted pads, and SMD problems.",
    "action": "Identify at least four defect types from visual examples before touching the iron."
  },
  {
    "id": "nasa-esd",
    "week": 5,
    "type": "Written",
    "status": "Required",
    "title": "NASA-HDBK-8739.21 — ESD Control",
    "provider": "NASA",
    "url": "https://standards.nasa.gov/safety-quality-reliability-maintainability",
    "focus": "ESD controls as a distinct workmanship concern.",
    "action": "Set up an ESD-safe work routine and list what it does—and does not—protect against."
  },
  {
    "id": "nasa-harness",
    "week": 5,
    "type": "Written",
    "status": "Required",
    "title": "NASA-STD-8739.4 — Crimping, Interconnecting Cables, Harnesses, and Wiring",
    "provider": "NASA",
    "url": "https://standards.nasa.gov/node/283",
    "focus": "Termination, crimping, strain relief, interconnect workmanship, and inspection.",
    "action": "Use the standard as a workmanship reference; do not claim certification from reading it."
  },
  {
    "id": "saleae-digital",
    "week": 6,
    "type": "Written",
    "status": "Required",
    "title": "Logic Analyzer Learning and Support",
    "provider": "Saleae",
    "url": "https://www.saleae.com/support",
    "focus": "Digital capture, sampling, channel mapping, and decoding workflow.",
    "action": "Capture a known-good digital signal before using the analyzer on a fault."
  },
  {
    "id": "sparkfun-i2c",
    "week": 7,
    "type": "Written",
    "status": "Required",
    "title": "I²C Tutorial",
    "provider": "SparkFun Learn",
    "url": "https://learn.sparkfun.com/tutorials/i2c",
    "focus": "SDA/SCL, pull-ups, addressing, start/stop, and ACK/NACK.",
    "action": "Label SDA, SCL, pull-ups, address, and one expected transaction on your setup."
  },
  {
    "id": "saleae-i2c",
    "week": 7,
    "type": "Written",
    "status": "Required",
    "title": "STM32 Nucleo Board — Analyzing I2C",
    "provider": "Saleae",
    "url": "https://www.saleae.com/support/tutorials-learning/example-projects/how-to-analyze-i2c",
    "focus": "Known-good I²C capture and decoder evidence.",
    "action": "Decode one identity-register or equivalent read and save the capture."
  },
  {
    "id": "sparkfun-spi",
    "week": 7,
    "type": "Written",
    "status": "Required",
    "title": "Serial Peripheral Interface (SPI)",
    "provider": "SparkFun Learn",
    "url": "https://learn.sparkfun.com/tutorials/serial-peripheral-interface-spi/",
    "focus": "Clock, data, chip select, controller/peripheral roles, and timing mode.",
    "action": "Identify SCK, data lines, CS, and the timing mode required by one datasheet."
  },
  {
    "id": "saleae-spi",
    "week": 7,
    "type": "Written",
    "status": "Required",
    "title": "STM32 Nucleo Board — Analyzing SPI",
    "provider": "Saleae",
    "url": "https://www.saleae.com/support/tutorials-learning/example-projects/how-to-analyze-spi",
    "focus": "SPI capture and decoder setup.",
    "action": "Capture one known-good SPI transaction and verify framing against the datasheet."
  },
  {
    "id": "st-training",
    "week": 8,
    "type": "Video",
    "status": "Review",
    "title": "STM32 Online Training",
    "provider": "STMicroelectronics",
    "url": "https://www.st.com/content/st_com/en/support/learning/stm32-online-training.html",
    "focus": "MCU ecosystem, clocks, peripherals, and debug context.",
    "action": "Use only the sections needed for the capstone hardware; Jade does not require the full STM32 curriculum."
  },
  {
    "id": "st-cubemx",
    "week": 8,
    "type": "Video",
    "status": "Review",
    "title": "STM32CubeMX & CubeHAL Basics MOOC",
    "provider": "STMicroelectronics",
    "url": "https://www.st.com/content/st_com/en/support/learning/stm32-moocs/stm32cubemx-and-cubeHhal-basics.html",
    "focus": "GPIO, UART, SPI, timers, ADC, and generated configuration.",
    "action": "Treat this as capstone support, not a prerequisite for the technician core."
  },
  {
    "id": "aac-ground-reference",
    "week": 1,
    "type": "Video",
    "status": "Required",
    "title": "Ground and Other Reference Points",
    "provider": "North Seattle Community College / All About Circuits",
    "url": "https://www.allaboutcircuits.com/video-lectures/ground-reference-points/",
    "focus": "Voltage reference, polarity, and probe-order interpretation.",
    "action": "Predict the sign of a meter reading from the chosen reference and probe order."
  },
  {
    "id": "aac-current-path",
    "week": 1,
    "type": "Video",
    "status": "Required",
    "title": "Basic Requirements for Current",
    "provider": "North Seattle Community College / All About Circuits",
    "url": "https://www.allaboutcircuits.com/video-lectures/basic-requirements-for-current/",
    "focus": "Closed paths, source/load/return, and why an open path stops current.",
    "action": "Trace the complete current path in the Core 1 practical before calculating."
  },
  {
    "id": "aac-ohms-written",
    "week": 1,
    "type": "Written",
    "status": "Required",
    "title": "Ohm’s Law — How Voltage, Current, and Resistance Relate",
    "provider": "All About Circuits",
    "url": "https://www.allaboutcircuits.com/textbook/direct-current/chpt-2/voltage-current-resistance-relate/",
    "focus": "Physical meaning of voltage/current/resistance and Ohm’s law",
    "action": "Rework one Jade DC example from the written explanation without looking at the lesson."
  },
  {
    "id": "sparkfun-schematic",
    "week": 2,
    "type": "Written",
    "status": "Required",
    "title": "How to Read a Schematic",
    "provider": "SparkFun Learn",
    "url": "https://learn.sparkfun.com/tutorials/how-to-read-a-schematic/overview",
    "focus": "Symbols, nets, nodes, labels, designators, schematic-to-circuit reading",
    "action": "Trace one Jade schematic path and identify three named nets or nodes."
  },
  {
    "id": "sparkfun-pcb",
    "week": 2,
    "type": "Written",
    "status": "Required",
    "title": "PCB Basics",
    "provider": "SparkFun Learn",
    "url": "https://learn.sparkfun.com/tutorials/pcb-basics",
    "focus": "Pads, traces, vias, planes, through-hole and surface-mount anatomy",
    "action": "Point out pads, traces, vias and at least one likely test point on a real or photographed PCB."
  },
  {
    "id": "digikey-datasheet-video",
    "week": 2,
    "type": "Video",
    "status": "Required",
    "title": "How To Read A Datasheet",
    "provider": "DigiKey Electronics",
    "url": "https://www.digikey.com/en/videos/d/digi-key-electronics/how-to-read-a-datasheet-electronics-with-becky-stern-digikey",
    "focus": "Pinouts, ratings, tables, limits, and finding the specific answer you need",
    "action": "Answer one exact engineering question from a real component datasheet."
  },
  {
    "id": "tek-scope-webinar",
    "week": 3,
    "type": "Video",
    "status": "Required",
    "title": "How to Get the Most Out of Your Oscilloscope",
    "provider": "Tektronix",
    "url": "https://www.tek.com/en/video/webinar/how-to-get-the-most-out-of-your-oscilloscope",
    "focus": "Vertical, horizontal, trigger and probing fundamentals",
    "action": "Configure a known waveform manually before using Autoset."
  },
  {
    "id": "aac-troubleshooting-tips",
    "week": 4,
    "type": "Written",
    "status": "Required",
    "title": "General Troubleshooting Tips",
    "provider": "All About Circuits",
    "url": "https://www.allaboutcircuits.com/textbook/reference/chpt-8/general-troubleshooting-tips/",
    "focus": "Observation, history, probability and disciplined fault isolation",
    "action": "List three plausible causes before touching the circuit."
  },
  {
    "id": "aac-troubleshooting-specific",
    "week": 4,
    "type": "Written",
    "status": "Required",
    "title": "Specific Troubleshooting Techniques",
    "provider": "All About Circuits",
    "url": "https://www.allaboutcircuits.com/textbook/reference/chpt-8/specific-troubleshooting-techniques/",
    "focus": "Divide-and-conquer, substitution, stage boundaries and signal tracing",
    "action": "Choose a boundary measurement that would eliminate at least one hypothesis."
  },
  {
    "id": "digikey-solder-video",
    "week": 5,
    "type": "Video",
    "status": "Required",
    "title": "How To Solder — Electronics with Becky Stern",
    "provider": "DigiKey Electronics",
    "url": "https://www.digikey.com/en/videos/d/digi-key-electronics/how-to-solder-electronics-with-becky-stern-digi-key-electronics",
    "focus": "Heating both surfaces, solder flow, wetting and joint formation",
    "action": "Inspect your next joint specifically for wetting and concave geometry."
  },
  {
    "id": "aac-logic-video",
    "week": 6,
    "type": "Video",
    "status": "Required",
    "title": "Logic Gates — Logic States",
    "provider": "North Seattle Community College / All About Circuits",
    "url": "https://www.allaboutcircuits.com/video-lectures/logic-gates-logic-states/",
    "focus": "Logic states as physical voltage levels",
    "action": "Translate one HIGH/LOW statement into expected voltages for the device you are using."
  },
  {
    "id": "aac-logic-levels",
    "week": 6,
    "type": "Written",
    "status": "Required",
    "title": "Logic Signal Voltage Levels",
    "provider": "All About Circuits",
    "url": "https://www.allaboutcircuits.com/textbook/digital/chpt-3/logic-signal-voltage-levels/",
    "focus": "VIH/VIL ranges, margins, and why logic is not simply exact 0 V / VCC",
    "action": "Find VIH and VIL in one real datasheet and write the valid ranges."
  },
  {
    "id": "aac-cmos-pulls",
    "week": 6,
    "type": "Written",
    "status": "Required",
    "title": "CMOS Gate Circuitry — Floating Inputs and Pull Resistors",
    "provider": "All About Circuits",
    "url": "https://www.allaboutcircuits.com/textbook/digital/chpt-3/cmos-gate-circuitry/",
    "focus": "Floating inputs and pull-up/pull-down behavior",
    "action": "Predict the default state before and after adding a pull resistor."
  },
  {
    "id": "ti-debounce-video",
    "week": 6,
    "type": "Video",
    "status": "Required",
    "title": "Debounce a Switch",
    "provider": "Texas Instruments",
    "url": "https://www.ti.com/video/5840441551001",
    "focus": "Mechanical bounce as a time-domain problem",
    "action": "Identify repeated transitions in a captured switch event."
  },
  {
    "id": "saleae-capture-video",
    "week": 6,
    "type": "Video",
    "status": "Required",
    "title": "Logic 2 Tutorial — Capturing Data",
    "provider": "Saleae Support",
    "url": "https://www.youtube.com/watch?v=XhWKoFj_p9k",
    "focus": "Sampling rate, thresholds, channels and saving captures",
    "action": "Capture one known-good digital signal with labeled channels."
  },
  {
    "id": "saleae-protocol-video",
    "week": 7,
    "type": "Video",
    "status": "Required",
    "title": "Logic 2 Tutorial — Protocol Analyzers",
    "provider": "Saleae Support",
    "url": "https://www.youtube.com/watch?v=Ak9R4yxQPhs",
    "focus": "Protocol decoder setup and correlating decoded data with raw edges",
    "action": "Decode one transaction, then inspect the raw waveform under the decoder result."
  },
  {
    "id": "ti-uart-video",
    "week": 7,
    "type": "Video",
    "status": "Required",
    "title": "UART Protocol and Error Overview",
    "provider": "Texas Instruments",
    "url": "https://www.ti.com/video/6313217959112",
    "focus": "Start/stop/parity framing, baud rate and timing-error sources",
    "action": "Label a UART frame and state what framing assumption the decoder needs."
  }
];
