window.JADE_RESOURCES = [
  {
    "id": "aac-electrical-a",
    "week": 1,
    "type": "Video",
    "status": "Required",
    "title": "Electrical Quantities A — Voltage, Current, Resistance, and Charge",
    "provider": "North Seattle Community College / All About Circuits",
    "url": "https://www.allaboutcircuits.com/video-lectures/electrical-quantities-a/",
    "focus": "Physical meaning of voltage, current, resistance, and charge.",
    "action": "Explain each quantity in plain language and state whether it is measured across or through a circuit."
  },
  {
    "id": "aac-electrical-b",
    "week": 1,
    "type": "Video",
    "status": "Required",
    "title": "Electrical Quantities B — Ohm’s Law and Electrical Power",
    "provider": "North Seattle Community College / All About Circuits",
    "url": "https://www.allaboutcircuits.com/video-lectures/electrical-quantities-b/",
    "focus": "Ohm’s law, direct/inverse relationships, and power.",
    "action": "Predict the relationship before calculating; then verify the units."
  },
  {
    "id": "aac-notation",
    "week": 1,
    "type": "Video",
    "status": "Required",
    "title": "Technical Notation — Engineering Notation and SI Prefixes",
    "provider": "North Seattle Community College / All About Circuits",
    "url": "https://www.allaboutcircuits.com/video-lectures/technical-notation/",
    "focus": "milli, micro, nano, kilo, mega, and engineering notation.",
    "action": "Convert at least ten values between base units and common prefixes."
  },
  {
    "id": "fluke-dmm",
    "week": 3,
    "type": "Written",
    "status": "Required",
    "title": "How to Use a Multimeter — Comprehensive Guide",
    "provider": "Fluke",
    "url": "https://www.fluke.com/en/learn/blog/maintenance-monitoring/how-to-use-a-multimeter-guide",
    "focus": "DMM functions, jacks, continuity, resistance, voltage, diode test, and safety.",
    "action": "Before the next measurement, say quantity → function → jack → connection → expected reading."
  },
  {
    "id": "keysight-psu",
    "week": 3,
    "type": "Video",
    "status": "Required",
    "title": "Bench Power Supply Basics",
    "provider": "Keysight Technologies",
    "url": "https://www.keysight.com/us/en/learn/course.bench-power-supply-basics.html",
    "focus": "Voltage setting, current limit, CV/CC behavior, and safe first power.",
    "action": "Set a conservative current limit and predict whether the supply should remain in CV mode."
  },
  {
    "id": "keysight-cvcc",
    "week": 3,
    "type": "Video",
    "status": "Required",
    "title": "Constant Voltage and Constant Current Modes",
    "provider": "Keysight Technologies",
    "url": "https://www.keysight.com/zz/en/assets/6123-1426/lessons/0027BenchPowerSupplyBasics004Using6UnderstandingConstantVoltageandConstantCurrentModes.html",
    "focus": "Interpret current-limit behavior as evidence, not as a setting to defeat.",
    "action": "Explain what a sudden switch into CC mode tells you about the load."
  },
  {
    "id": "tektronix-scope",
    "week": 3,
    "type": "Written",
    "status": "Required",
    "title": "How to Use an Oscilloscope and Probe — Step-by-Step",
    "provider": "Tektronix",
    "url": "https://www.tek.com/en/documents/primer/setting-and-using-oscilloscope",
    "focus": "Grounding, probe connection, volts/div, time/div, triggering, probe compensation, and basic measurement.",
    "action": "Capture a known square wave and preserve the settings that make the capture reproducible."
  },
  {
    "id": "aac-kcl-kvl",
    "week": 2,
    "type": "Video",
    "status": "Required",
    "title": "Ohm’s Law, Kirchhoff’s Laws, and Power Equations",
    "provider": "All About Circuits",
    "url": "https://www.youtube.com/watch?v=ezvZuaVzoys",
    "focus": "KCL/KVL as conservation rules and diagnostic tools.",
    "action": "Write the signed equation before substituting numbers."
  },
  {
    "id": "aac-troubleshoot",
    "week": 4,
    "type": "Video",
    "status": "Required",
    "title": "Troubleshooting Series-Parallel Circuits",
    "provider": "North Seattle Community College / All About Circuits",
    "url": "https://www.allaboutcircuits.com/video-lectures/troubleshooting-series-parallel-circuits/",
    "focus": "Expected values, fault patterns, and measurements that shrink the fault space.",
    "action": "Write expected values before taking the next troubleshooting measurement."
  },
  {
    "id": "ti-board",
    "week": 4,
    "type": "Video",
    "status": "Required",
    "title": "Board Level Troubleshooting",
    "provider": "Texas Instruments",
    "url": "https://www.ti.com/video/5971802514001",
    "focus": "Board-level troubleshooting and controlled substitution.",
    "action": "Identify what evidence a substitution would prove and what it would not prove."
  },
  {
    "id": "adafruit-solder",
    "week": 5,
    "type": "Written",
    "status": "Required",
    "title": "Making a Good Solder Joint",
    "provider": "Adafruit Learning System",
    "url": "https://learn.adafruit.com/adafruit-guide-excellent-soldering/making-a-good-solder-joint",
    "focus": "Heating the joint, solder flow, cooling, and workmanship.",
    "action": "Produce and inspect five joints before attempting rework."
  },
  {
    "id": "adafruit-defects",
    "week": 5,
    "type": "Written",
    "status": "Required",
    "title": "Common Soldering Problems",
    "provider": "Adafruit Learning System",
    "url": "https://learn.adafruit.com/adafruit-guide-excellent-soldering/common-problems",
    "focus": "Cold/disturbed joints, bridges, insufficient wetting, excess solder, lifted pads, and SMD problems.",
    "action": "Identify at least four defect types from visual examples before touching the iron."
  },
  {
    "id": "nasa-esd",
    "week": 5,
    "type": "Written",
    "status": "Required",
    "title": "NASA-HDBK-8739.21 — ESD Control",
    "provider": "NASA",
    "url": "https://standards.nasa.gov/safety-quality-reliability-maintainability",
    "focus": "ESD controls as a distinct workmanship concern.",
    "action": "Set up an ESD-safe work routine and list what it does—and does not—protect against."
  },
  {
    "id": "nasa-harness",
    "week": 5,
    "type": "Written",
    "status": "Required",
    "title": "NASA-STD-8739.4 — Crimping, Interconnecting Cables, Harnesses, and Wiring",
    "provider": "NASA",
    "url": "https://standards.nasa.gov/node/283",
    "focus": "Termination, crimping, strain relief, interconnect workmanship, and inspection.",
    "action": "Use the standard as a workmanship reference; do not claim certification from reading it."
  },
  {
    "id": "saleae-digital",
    "week": 6,
    "type": "Written",
    "status": "Required",
    "title": "Logic Analyzer Learning and Support",
    "provider": "Saleae",
    "url": "https://www.saleae.com/support",
    "focus": "Digital capture, sampling, channel mapping, and decoding workflow.",
    "action": "Capture a known-good digital signal before using the analyzer on a fault."
  },
  {
    "id": "sparkfun-i2c",
    "week": 7,
    "type": "Written",
    "status": "Required",
    "title": "I²C Tutorial",
    "provider": "SparkFun Learn",
    "url": "https://learn.sparkfun.com/tutorials/i2c",
    "focus": "SDA/SCL, pull-ups, addressing, start/stop, and ACK/NACK.",
    "action": "Label SDA, SCL, pull-ups, address, and one expected transaction on your setup."
  },
  {
    "id": "saleae-i2c",
    "week": 7,
    "type": "Written",
    "status": "Required",
    "title": "STM32 Nucleo Board — Analyzing I2C",
    "provider": "Saleae",
    "url": "https://www.saleae.com/support/tutorials-learning/example-projects/how-to-analyze-i2c",
    "focus": "Known-good I²C capture and decoder evidence.",
    "action": "Decode one identity-register or equivalent read and save the capture."
  },
  {
    "id": "sparkfun-spi",
    "week": 7,
    "type": "Written",
    "status": "Required",
    "title": "Serial Peripheral Interface (SPI)",
    "provider": "SparkFun Learn",
    "url": "https://learn.sparkfun.com/tutorials/serial-peripheral-interface-spi/",
    "focus": "Clock, data, chip select, controller/peripheral roles, and timing mode.",
    "action": "Identify SCK, data lines, CS, and the timing mode required by one datasheet."
  },
  {
    "id": "saleae-spi",
    "week": 7,
    "type": "Written",
    "status": "Required",
    "title": "STM32 Nucleo Board — Analyzing SPI",
    "provider": "Saleae",
    "url": "https://www.saleae.com/support/tutorials-learning/example-projects/how-to-analyze-spi",
    "focus": "SPI capture and decoder setup.",
    "action": "Capture one known-good SPI transaction and verify framing against the datasheet."
  },
  {
    "id": "st-training",
    "week": 8,
    "type": "Video",
    "status": "Review",
    "title": "STM32 Online Training",
    "provider": "STMicroelectronics",
    "url": "https://www.st.com/content/st_com/en/support/learning/stm32-online-training.html",
    "focus": "MCU ecosystem, clocks, peripherals, and debug context.",
    "action": "Use only the sections needed for the capstone hardware; Jade does not require the full STM32 curriculum."
  },
  {
    "id": "st-cubemx",
    "week": 8,
    "type": "Video",
    "status": "Review",
    "title": "STM32CubeMX & CubeHAL Basics MOOC",
    "provider": "STMicroelectronics",
    "url": "https://www.st.com/content/st_com/en/support/learning/stm32-moocs/stm32cubemx-and-cubeHhal-basics.html",
    "focus": "GPIO, UART, SPI, timers, ADC, and generated configuration.",
    "action": "Treat this as capstone support, not a prerequisite for the technician core."
  },
  {
    "id": "aac-ground-reference",
    "week": 1,
    "type": "Video",
    "status": "Required",
    "title": "Ground and Other Reference Points",
    "provider": "North Seattle Community College / All About Circuits",
    "url": "https://www.allaboutcircuits.com/video-lectures/ground-reference-points/",
    "focus": "Voltage reference, polarity, and probe-order interpretation.",
    "action": "Predict the sign of a meter reading from the chosen reference and probe order."
  },
  {
    "id": "aac-current-path",
    "week": 1,
    "type": "Video",
    "status": "Required",
    "title": "Basic Requirements for Current",
    "provider": "North Seattle Community College / All About Circuits",
    "url": "https://www.allaboutcircuits.com/video-lectures/basic-requirements-for-current/",
    "focus": "Closed paths, source/load/return, and why an open path stops current.",
    "action": "Trace the complete current path in the Core 1 practical before calculating."
  }
];
